name: Setup Node.js with cache
description: Sets up Node.js, caches node_modules and npm, and installs dependencies if needed.

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc

    - name: Compute node modules cache key
      id: nodeModulesCacheKey
      shell: bash
      run: echo "value=$(sha256sum package-lock.json | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

    - name: Cache node modules
      id: cacheNodeModules
      uses: actions/cache@v5
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-cacheNodeModules20-${{ steps.nodeModulesCacheKey.outputs.value }}
        restore-keys: ${{ runner.os }}-cacheNodeModules20-

    - name: Get npm cache directory path
      id: npmCacheDirPath
      if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - name: Cache npm directory
      if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
      uses: actions/cache@v5
      with:
        path: ${{ steps.npmCacheDirPath.outputs.dir }}
        key: ${{ runner.os }}-npmCacheDir-${{ steps.nodeModulesCacheKey.outputs.value }}
        restore-keys: ${{ runner.os }}-npmCacheDir-

    - name: Install system dependencies
      if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libxkbfile-dev pkg-config libkrb5-dev libxss1

    - name: Install npm dependencies
      if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        ELECTRON_SKIP_BINARY_DOWNLOAD: 1
      run: npm ci --ignore-scripts

    - name: Install build tool dependencies
      if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
      shell: bash
      run: cd build && npm ci --ignore-scripts
